# vim: ft=python

Import("env")

tests = ['region-test',
         'scaling-test',
         #C99 'fetch-test',
         'oob-test',
         'window-test',
         #glib.h 'trap-test'
         ]

for t in tests:
    e = env.Clone(PDB = t + '.pdb')
    e.Program(t, t + '.c', LIBS = 'pixman.lib', LIBPATH='#pixman')
